apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Values.service.name }}
    tier: {{ .Values.service.tier }}

