apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: mspace
spec:
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
      - name: nginx
        image: "mujeeb/frontend-docker"
        imagePullPolicy: Never  #change this to 'Always' when fetching the image from registry
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]